name: loan-mortgage-calculator
region: nyc

services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    
    build_command: npm ci && npm run build
    run_command: npm start
    
    envs:
      - key: NODE_ENV
        value: production
    
    http_port: 8080
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
